services:
  - type: web
    name: sophy-web-os
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: SOPHY_SUDO_PASSWORD
        sync: false
